### ISSUE TITLE
Using/activating this plugin

### ISSUE THREAD

**Issue by furroy** [steelbrain/busy-signal#10]
I have a custom linter I'm working on. It calls out to a 3rd party executable which lints an entire project at once, usually taking several seconds. So this busy feedback would really be useful.  I installed linter, linter-ui-default, and busy-signal.  Nothing seems to change during the lint process. I got the impression linter would auto-magically  activate this busy behavior when everything was installed.  Or do I need to manually call this plugin myself in my code?

**Comment by steelbrain** [comment]
Hi @furroy,
How did you install `linter` and `linter-ui-default`? You need to uninstall the APM versions and install the versions from their git repos for them to work with this package.

Commands for bash to do all of this can be found in [`linter-ui-default` README](https://github.com/steelbrain/linter-ui-default#installation)

**Comment by furroy** [comment]
Ah all right. I saw that, but I thought it was an example of how you could install things, it wasn't clear to me it was required to be installed that way.  This will get me the v2 of linter and I'll have to migrate my plugin if I go this route correct?

**Comment by steelbrain** [comment]
Busy signal will work with both v1 and v2 providers regardless of if you upgrade or not. Upgrading should give you a better message type though, but if you publish an update using the v2 API it won't work for anyone because v2 is not yet published.

and Yes, it will get you v2 of linter and master of linter-ui-default

**Comment by steelbrain** [comment]
Closing as answered, feel free to continue discussion
