### ISSUE TITLE
Automatically hide the icon while no action is performed

### ISSUE THREAD

**Issue by MoritzKn** [steelbrain/busy-signal#27]
It would be nice to have a option to automatically hide the icon in the status bar while no action is performed.
This is somewhat related to #12, but distinct because I would like to still see the icon while something is actual busy.

**Comment by MoritzKn** [comment]
I was able to achieve this by adding this to my styles file:
```css
busy-signal.idle { display: none !important;
}
```
Feel free to close this, but perhaps a built in option is still desirable.

**Comment by steelbrain** [comment]
Outdated as of https://github.com/steelbrain/busy-signal/pull/29 because the styles don't change much, but even if you'd still like to hide it, you've already posted the css :)

**Comment by mehcode** [comment]
@steelbrain I think this is still quite important. It doesn't make sense to me to see a green dot on the status bar. A _progress indication_ should really only show when there is progress to indicate.

I looked at a few other editors:
 - VS Code
 - Android Studio
 - Xcode

All of them do have progress indicators and they only show when actual progress is being made.
