### ISSUE TITLE
Editor flickers when busy signal animating

### ISSUE THREAD

**Issue by AshKyd** [steelbrain/busy-signal#28]
I have been getting flickering in my Atom editor when the busy signal is running.

The following screenshot shows the behaviour when hitting ctrl+s to trigger an eslint+busy signal:

[![editor flashes on save](http://i.imgur.com/afVbmZx.gif)](http://i.imgur.com/afVbmZx.gif)

I have the following configuration:

|Thing|Description|
| ------------- | ------------- |
| OS              | Linux/Fedora/Gnome 3 (maybe it's a Linux thing?) |
| Atom            | 1.17.0 (freshly installed yesterday) |
| Extra installed packages | docblockr linter linter-eslint linter-ui-default intentions busy-signal |

Notes:
* Using a default linter/eslint setup, the editor starts flashing when the busy signal is animating.
* The problem is not/barely noticeable on a freshly started Atom but gets worse with time.
* Disabling the busy signal package alone makes the problem stop happening. Re-enabling it brings it back.

You may be able to reproduce this by:
1. install a fresh copy of Atom
2. `apm install docblockr linter linter-eslint linter-ui-default intentions busy-signal`
3. check out & NPM install a repo with an .eslintrc (eg. [the one I'm using](https://github.com/abcnews/chatfuel-feed-reader))
4. Open a JS file, then trigger an eslint by saving. Note that this doesn't seem to happen as often with a freshly opened Atom.

**Comment by steelbrain** [comment]
It's a problem with your Graphics drivers, make sure you have the correct drivers installed for your discrete GPU

**Comment by AshKyd** [comment]
Thanks for the speedy reply! I only have Intel graphics, so no discrete GPU. There's a kernel update waiting so I'll give that a try and see what happens.

Is this a known problem?

**Comment by steelbrain** [comment]
It's a problem with chromium having issues with certain drivers on Linux, not sure of a fix other than disabling GPU rendering entirely

**Comment by AshKyd** [comment]
Cool, consider this not a bug then. :)

**Comment by Decker108** [comment]
Can confirm this behavior on a Dell laptop running Intel Corporation Haswell-ULT Integrated Graphics Controller. Completely breaks the plugin and Atom for me, although it worked fine in plugin version 1.4.1.
