### ISSUE TITLE
Provide recent history list

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/busy-signal#4]
Most linter tasks are so brief the indication they are running is virtually instant, can a history of the X (3? 5?) most recent tasks be shown?

**Comment by steelbrain** [comment]
Interesting idea, Thanks!

**Comment by noseglid** [comment]
I have this in [my package](https://atom.io/packages/busy) which solves the same issue as this package and was created approximately the same time :)

**Comment by steelbrain** [comment]
@noseglid No offense but I really thought we could both work on one busy signal package instead of splitting the community in two 😄 but nevermind. Have fun working on yours

**Comment by noseglid** [comment]
Well, if you read what I said I stated that I wanted to follow through on
my idea and implementation [in the issue](
https://github.com/noseglid/atom-build/issues/421).
