### ISSUE TITLE
Duplicate rendered indicator

### ISSUE THREAD

**Issue by pascalduez** [steelbrain/busy-signal#51]
Hi,
while working the active indicator is being injected next to the inactive one.
I'm using the `atom-ide-ui` plugin.

![screenshot from 2018-04-15 10-25-32](https://user-images.githubusercontent.com/335467/38776520-6acd97ae-4098-11e8-9228-4a454f98561d.png)  

![screenshot from 2018-04-15 10-30-21](https://user-images.githubusercontent.com/335467/38776521-6e7f4da2-4098-11e8-9056-417ce4606f07.png)

```
$ atom --version
Atom    : 1.25.1
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
```

```
$ apm list --installed --bare
Sublime-Style-Column-Selection@1.7.4
atom-ide-ui@0.9.4
busy-signal@1.4.3
emmet@2.4.3
highlight-bad-chars@1.0.7
hyperclick@0.1.5
ide-flowtype@0.22.1
ide-flowtype-coverage@1.9.2
language-babel@2.84.0
language-reason@0.0.4
language-rust@0.4.12
linter@2.2.0
linter-eslint@8.4.1
linter-pycodestyle@2.1.3
linter-rust@0.8.4
linter-stylelint@4.2.0
minimap@4.29.8
ocaml-merlin@0.14.4
prettier-atom@0.53.0
sort-lines@0.18.0
svg-preview@0.12.1
terminal-tab@0.5.5
```

**Comment by Arcanemagus** [comment]
`atom-ide-ui` uses their own busy indicator instead of this one.
