### ISSUE TITLE
Disallow selection of status icon

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/busy-signal#7]
Reported by Mike Garret on Slack

Gif: ![repro of error](https://my.cl.ly/content/hQYJ)

**Comment by MikeNGarrett** [comment]
Context: linter is running, so icon is currently orange and spinning. 
Steps to reproduce: Ensure Atom's chrome is active. Mouse over status icon while it's rotating.

**Comment by steelbrain** [comment]
I'm unable to repro this in the Atom {Dark,Light} Themes. Can you tell us the theme you're using?

**Comment by steelbrain** [comment]
After some debugging, we found it to be a theme issue.
