### ISSUE TITLE
`document.registerElement` doesn't work in Electron 11, which is planned to be used in Atom soonish

### ISSUE THREAD

**Issue by DeeDeeG** [steelbrain/busy-signal#90]
Hi folks, I thought I would give some heads up about something. `document.registerElement` (Custom Elements v0) is not supported by Electron 11, in favor of Custom Elements v1. Atom is looking to move to Electron 11 soonish: https://github.com/atom/atom/pull/22687

<details><summary>More context, and documentation/references/resources (click to expand)</summary>

`document.registerElement` is part of Custom Elements v0. That is being slowly deprecated and removed from the web platform in favor of the consensus standard Custom Elements v1 [\[1\]][Custom Elements v0 deprecation].

It was finally removed from recent versions of Chromium/Chrome, and thus also recent versions of Electron.

(It was removed in Chromium/Chrome 86 [\[2\]][chromium deprecation], which then carries over to Electron 11 [\[3\]][electron deprecation])

[Custom Elements v0 deprecation]: https://www.chromestatus.com/feature/4642138092470272
[Chromium deprecation]: https://developers.google.com/web/updates/2020/09/chrome-86-deps-rems#remove_webcomponents_v0
[Electron deprecation]: https://www.electronjs.org/releases/stable?version=11&page=6

Atom has an open PR exploring the potential move to Electron 11 (https://github.com/atom/atom/pull/22687#issuecomment-904013240), but this means a breaking change dropping `document.registerElement` support from Atom. I thought I would post an issue here to let you folks know about it, since I understand this is used by some other important packages in the Atom ecosystem.

Here is a comment with some resources about Custom Elements v1:
https://github.com/atom/atom/pull/22011#issuecomment-799738887

</details>

Here are some example PRs showing how to migrate (coincidentally, most of these are from Atom core, but the code pattern applies to any recent JS environment):

<details><summary>Example PRs (click to expand)</summary>

- https://github.com/atom-community/terminal/pull/70
- https://github.com/atom/atom/pull/22749
- https://github.com/atom/atom/pull/22750
- https://github.com/atom/atom/pull/22751
- https://github.com/atom/atom/pull/22755
- https://github.com/atom/atom/pull/22769
- https://github.com/atom/atom/pull/22774
- https://github.com/atom/atom/pull/22780
- https://github.com/atom/atom/pull/22785
- https://github.com/atom/atom/pull/22787
- https://github.com/atom/atom/pull/22789
- https://github.com/atom/atom/pull/22867

Some specs might need some modification to attach things to the DOM? For example:
- https://github.com/atom/tree-view/pull/1392

</details>

I'm not much of a JS expert myself, so I don't now how helpful those examples will be. but I see Custom Elements v0 is being used in this package at these locations in the code:
- https://github.com/steelbrain/busy-signal/blob/v2.0.1/lib/element.js
- https://github.com/steelbrain/busy-signal/blob/v2.0.1/lib/main.js#L6
- https://github.com/steelbrain/busy-signal/blob/v2.0.1/spec/element-spec.js#L3

**Comment by DeeDeeG** [comment]
Maybe I posted this too soon. See [this comment](https://github.com/atom/atom/pull/22687#issuecomment-905205222) regarding if there is a way to provide `document.registerElement` in Atom, such as with a polyfill.

**Comment by steelbrain** [comment]
Taken care of, thank you
